[package]
name = "frospy"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.3"
clap = { version = "4.5.37", features = ["derive"] }
itertools = "0.14.0"
rand = "0.9.0"
rpds = "1.1.0"
thiserror = "1.0.61"
